// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show
        defaultTargetPlatform,
        kIsWeb,
        TargetPlatform;

/// Default Firebase Options
class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {

    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {

      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
        return macos;

      case TargetPlatform.windows:
        return windows;

      case TargetPlatform.linux:
        throw UnsupportedError(
          'Linux Firebase not configured.',
        );

      default:
        throw UnsupportedError(
          'Platform not supported.',
        );
    }
  }

  // =========================
  // WEB
  // =========================

  static const FirebaseOptions web =
      FirebaseOptions(

    apiKey:
        'AIzaSyCxwjpIrCXBPl6xx_hhlkngbnXUkYEk_T4',

    appId:
        '1:551540707255:web:da03ab982f688a20e12232',

    messagingSenderId:
        '551540707255',

    projectId:
        'trackshieldai',

    authDomain:
        'trackshieldai.firebaseapp.com',

    storageBucket:
        'trackshieldai.firebasestorage.app',

    measurementId:
        'G-03ERFTCTHK',

    databaseURL:
        'https://trackshieldai-default-rtdb.firebaseio.com/',
  );

  // =========================
  // ANDROID
  // =========================

  static const FirebaseOptions android =
      FirebaseOptions(

    apiKey:
        'AIzaSyAm3tTMlAUMLf19bP7BjSu5FAiqazOMr3E',

    appId:
        '1:551540707255:android:3c7ce5632becb49be12232',

    messagingSenderId:
        '551540707255',

    projectId:
        'trackshieldai',

    storageBucket:
        'trackshieldai.firebasestorage.app',

    databaseURL:
        'https://trackshieldai-default-rtdb.firebaseio.com/',
  );

  // =========================
  // IOS
  // =========================

  static const FirebaseOptions ios =
      FirebaseOptions(

    apiKey:
        'AIzaSyBO9BAyEJhBFmF1ZQof7t2iGd3Z_vqDmV0',

    appId:
        '1:551540707255:ios:7ea508ecce5a3b1ae12232',

    messagingSenderId:
        '551540707255',

    projectId:
        'trackshieldai',

    storageBucket:
        'trackshieldai.firebasestorage.app',

    iosBundleId:
        'com.example.mobileApp',

    databaseURL:
        'https://trackshieldai-default-rtdb.firebaseio.com/',
  );

  // =========================
  // MACOS
  // =========================

  static const FirebaseOptions macos =
      FirebaseOptions(

    apiKey:
        'AIzaSyBO9BAyEJhBFmF1ZQof7t2iGd3Z_vqDmV0',

    appId:
        '1:551540707255:ios:7ea508ecce5a3b1ae12232',

    messagingSenderId:
        '551540707255',

    projectId:
        'trackshieldai',

    storageBucket:
        'trackshieldai.firebasestorage.app',

    iosBundleId:
        'com.example.mobileApp',

    databaseURL:
        'https://trackshieldai-default-rtdb.firebaseio.com/',
  );

  // =========================
  // WINDOWS
  // =========================

  static const FirebaseOptions windows =
      FirebaseOptions(

    apiKey:
        'AIzaSyCxwjpIrCXBPl6xx_hhlkngbnXUkYEk_T4',

    appId:
        '1:551540707255:web:517eda6e33bf9746e12232',

    messagingSenderId:
        '551540707255',

    projectId:
        'trackshieldai',

    authDomain:
        'trackshieldai.firebaseapp.com',

    storageBucket:
        'trackshieldai.firebasestorage.app',

    measurementId:
        'G-9508T2G957',

    databaseURL:
        'https://trackshieldai-default-rtdb.firebaseio.com/',
  );
}