// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxwjpIrCXBPl6xx_hhlkngbnXUkYEk_T4',
    appId: '1:551540707255:web:da03ab982f688a20e12232',
    messagingSenderId: '551540707255',
    projectId: 'trackshieldai',
    authDomain: 'trackshieldai.firebaseapp.com',
    storageBucket: 'trackshieldai.firebasestorage.app',
    measurementId: 'G-03ERFTCTHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm3tTMlAUMLf19bP7BjSu5FAiqazOMr3E',
    appId: '1:551540707255:android:3c7ce5632becb49be12232',
    messagingSenderId: '551540707255',
    projectId: 'trackshieldai',
    storageBucket: 'trackshieldai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO9BAyEJhBFmF1ZQof7t2iGd3Z_vqDmV0',
    appId: '1:551540707255:ios:7ea508ecce5a3b1ae12232',
    messagingSenderId: '551540707255',
    projectId: 'trackshieldai',
    storageBucket: 'trackshieldai.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO9BAyEJhBFmF1ZQof7t2iGd3Z_vqDmV0',
    appId: '1:551540707255:ios:7ea508ecce5a3b1ae12232',
    messagingSenderId: '551540707255',
    projectId: 'trackshieldai',
    storageBucket: 'trackshieldai.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxwjpIrCXBPl6xx_hhlkngbnXUkYEk_T4',
    appId: '1:551540707255:web:517eda6e33bf9746e12232',
    messagingSenderId: '551540707255',
    projectId: 'trackshieldai',
    authDomain: 'trackshieldai.firebaseapp.com',
    storageBucket: 'trackshieldai.firebasestorage.app',
    measurementId: 'G-9508T2G957',
  );
}
